### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by Woolei** [shedaltd/react-native-azure-ad-2#9]
Hi Guys, 
i create a new expo project and copy paste the sample code in https://github.com/shedaltd/react-native-azure-ad-2/blob/master/example/App.js

but i receive the error below

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

![image](https://user-images.githubusercontent.com/6512444/60956991-6fc12080-a336-11e9-92ec-e348eee2b347.png)

can anyone show me how to configure for redirect uri?
this my configure in Azure App Registration
![image](https://user-images.githubusercontent.com/6512444/60956840-2cff4880-a336-11e9-9516-d9a71ba1979a.png)

this is my app.json setting in expo
![image](https://user-images.githubusercontent.com/6512444/60956921-4dc79e00-a336-11e9-9906-20fc591bc051.png)

**Comment by bpouliot** [comment]
I have the same issue. Is there a way to enable logging and see the details of what's being sent in the request? I have specified the "redirect_uri" param and registered that URL in Azure. No dice.

**Comment by bpouliot** [comment]
I registered my Redirect URI as the default, and it's working now:

https://localhost:3000/login

**Comment by Woolei** [comment]
yes it work!
![image](https://user-images.githubusercontent.com/6512444/61201866-665dfc80-a718-11e9-9310-0767aaf4e9f2.png)
